[tool.poetry]
name = "reactive-sympy"
version = "0.1.0"
description = ""
authors = ["Sharad Chand <pepsighan@sharadchand.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
